### ISSUE TITLE
Add support for ⌥-⌘-v (Paste style)

### ISSUE THREAD

**Issue by tallneil** [Evercoder/clipboard-inspector#12]
On Mac, ⌥-⌘-v (Option-Command-v) is the keyboard shortcut for Paste Style ([source](https://support.apple.com/en-us/102650)). 

I'd love to see what this writes to the clipboard using Clipboard Inspector.

**Comment by danburzo** [comment]
Unfortunately this entry of the system clipboard doesn’t seem to be exposed to the web in any browser I’ve tested on Mac.

**Comment by tallneil** [comment]
Bummer... thanks for trying
